question_data = {"response_code": 0, "results": [
    {"category": "Entertainment: Music", "type": "multiple", "difficulty": "easy",
     "question": "Who is the lead singer of the band Coldplay?", "correct_answer": "Chris Martin",
     "incorrect_answers": ["Chris Isaak", "Chris Wallace", "Chris Connelly"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "hard",
     "question": "This is the correct spelling of &quot;Supercalifragilisticexpialidocious&quot;.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Television", "type": "multiple", "difficulty": "medium",
     "question": "In Breaking Bad, the initials W.W. refer to which of the following?",
     "correct_answer": "Walter White", "incorrect_answers": ["William Wolf", "Willy Wonka", "Wally Walrus"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "In Super Mario Bros., who informs Mario that the princess is in another castle?",
     "correct_answer": "Toad", "incorrect_answers": ["Luigi", "Yoshi", "Bowser"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
     "question": "What does LTS stand for in the software market?", "correct_answer": "Long Term Support",
     "incorrect_answers": ["Long Taco Service", "Ludicrous Transfer Speed", "Ludicrous Turbo Speed"]},
    {"category": "Entertainment: Cartoon & Animations", "type": "multiple", "difficulty": "medium",
     "question": "Who created &quot;RWBY&quot;?", "correct_answer": "Monty Oum",
     "incorrect_answers": ["Miles Luna", "Kerry Shawcross", "Shane Newville"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple", "difficulty": "medium",
     "question": "Who is the creator of the manga series &quot;One Piece&quot;?", "correct_answer": "Eiichiro Oda",
     "incorrect_answers": ["Yoshihiro Togashi", "Hayao Miyazaki", "Masashi Kishimoto"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "Linus Sebastian is the creator of the Linux kernel, which went on to be used in Linux, Android, and Chrome OS.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "History", "type": "multiple", "difficulty": "medium",
     "question": "When was the Grand Patriotic War in the USSR concluded?", "correct_answer": "May 9th, 1945",
     "incorrect_answers": ["September 2nd, 1945", "August 9th, 1945", "December 11th, 1945"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "What zodiac sign is represented by a pair of scales?", "correct_answer": "Libra",
     "incorrect_answers": ["Aries", "Capricorn", "Sagittarius"]}]}
